//You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let Sarr = s.split('');
    let Tarr = t.split('');
    for(let i = 0; i < Tarr.length; i++){
        if(!(Sarr.includes(Tarr[i]))){
            return Tarr[i];
        }
        else{
            Sarr.splice(Sarr.indexOf(Tarr[i]), 1);
            Tarr.splice(i, 1);
            i--;
        }
    }
};

//We create arrays for s and t to be split into so we can easily remove elements. We use a for loop to
//traverse the array of t, since it is the larger of the two. We use an if statement to check if the
//array of s includes the current element we are checking for t. If it does not, this is the letter
//that was added, so we return it. Otherwise, we remove that letter from both arrays, and move on to
//check the next one. The problem has guaranteed that a letter was added into t, so no return statement
//was added for the situation where one is not found. 